# -*- coding: utf-8 -*-
LANG_CHN = '中文'
LANG_ENG = 'English'

E_FILE_CHN = '文件(&F)'
E_FILE_ENG = 'File(&F)'
E_FILE = {LANG_CHN: E_FILE_CHN, LANG_ENG: E_FILE_ENG}

E_IMPORT_APPS_INFO_CHN = '导入应用信息(&I)'
E_IMPORT_APPS_INFO_ENG = 'Import Info(&I)'
E_IMPORT_APPS_INFO = {LANG_CHN: E_IMPORT_APPS_INFO_CHN, LANG_ENG: E_IMPORT_APPS_INFO_ENG}

E_EXPORT_APPS_INFO_CHN = '导出应用信息(&X)'
E_EXPORT_APPS_INFO_ENG = 'Export Info(&X)'
E_EXPORT_APPS_INFO = {LANG_CHN: E_EXPORT_APPS_INFO_CHN, LANG_ENG: E_EXPORT_APPS_INFO_ENG}

E_QUIT_CHN = '退出(&Q)'
E_QUIT_ENG = 'Quit(&Q)'
E_QUIT = {LANG_CHN: E_QUIT_CHN, LANG_ENG: E_QUIT_ENG}

E_EDIT_CHN = '编辑(&E)'
E_EDIT_ENG = 'Edit(&E)'
E_EDIT = {LANG_CHN: E_EDIT_CHN, LANG_ENG: E_EDIT_ENG}

E_MANAGE_TAG_CHN = '管理标签(&M)'
E_MANAGE_TAG_ENG = 'Manage Tag(&M)'
E_MANAGE_TAG = {LANG_CHN: E_MANAGE_TAG_CHN, LANG_ENG: E_MANAGE_TAG_ENG}

E_NEW_TAG_CHN = '新建标签(&N)'
E_NEW_TAG_ENG = 'New Tag(&N)'
E_NEW_TAG = {LANG_CHN: E_MANAGE_TAG_CHN, LANG_ENG: E_MANAGE_TAG_ENG}

E_MOD_TAG_CHN = '编辑标签(&E)'
E_MOD_TAG_ENG = 'Edit Tag(&E)'
E_MOD_TAG = {LANG_CHN: E_MOD_TAG_CHN, LANG_ENG: E_MOD_TAG_ENG}

E_VIEW_CHN = '视图(&V)'
E_VIEW_ENG = 'View(&V)'
E_VIEW = {LANG_CHN: E_VIEW_CHN, LANG_ENG: E_VIEW_ENG}

E_SHOW_ICON_VIEW_CHN = '图标显示(&G)'
E_SHOW_ICON_VIEW_ENG = 'Show Icon(&G)'
E_SHOW_ICON_VIEW = {LANG_CHN: E_SHOW_ICON_VIEW_CHN, LANG_ENG: E_SHOW_ICON_VIEW_ENG}

E_SHOW_LIST_VIEW_CHN = '列表显示(&L)'
E_SHOW_LIST_VIEW_ENG = 'Show List(&L)'
E_SHOW_LIST_VIEW = {LANG_CHN: E_SHOW_LIST_VIEW_CHN, LANG_ENG: E_SHOW_LIST_VIEW_ENG}

E_OPTION_CHN = '选项(&S)'
E_OPTION_ENG = 'Option(&S)'
E_OPTION = {LANG_CHN: E_OPTION_CHN, LANG_ENG: E_OPTION_ENG}

E_SELECT_ROOT_CHN = '设置目录(&O)'
E_SELECT_ROOT_ENG = 'Select Root(&O)'
E_SELECT_ROOT = {LANG_CHN: E_SELECT_ROOT_CHN, LANG_ENG: E_SELECT_ROOT_ENG}

E_SELECT_THEME_CHN = '设置主题(&T)'
E_SELECT_THEME_ENG = 'Select Theme(&T)'
E_SELECT_THEME = {LANG_CHN: E_SELECT_THEME_CHN, LANG_ENG: E_SELECT_THEME_ENG}

E_SELECT_LANGUAGE_CHN = '设置语言(&T)'
E_SELECT_LANGUAGE_ENG = 'Select Language(&T)'
E_SELECT_LANGUAGE = {LANG_CHN: E_SELECT_LANGUAGE_CHN, LANG_ENG: E_SELECT_LANGUAGE_ENG}

E_SELECT_FONT_CHN = '设置字体(&F)'
E_SELECT_FONT_ENG = 'Select Font(&F)'
E_SELECT_FONT = {LANG_CHN: E_SELECT_FONT_CHN, LANG_ENG: E_SELECT_FONT_ENG}

E_SET_WINDOW_CHN = '设置窗口(&W)'
E_SET_WINDOW_ENG = 'Set Window(&W)'
E_SET_WINDOW = {LANG_CHN: E_SET_WINDOW_CHN, LANG_ENG: E_SET_WINDOW_ENG}

E_SHOW_LOCAL_APPS_CHN = '显示本地应用(&L)'
E_SHOW_LOCAL_APPS_ENG = 'Show Local Apps(&L)'
E_SHOW_LOCAL_APPS = {LANG_CHN: E_SHOW_LOCAL_APPS_CHN, LANG_ENG: E_SHOW_LOCAL_APPS_ENG}

E_HIDE_LOCAL_APPS_CHN = '隐藏本地应用(&L)'
E_HIDE_LOCAL_APPS_ENG = 'Hide Local Apps(&L)'
E_HIDE_LOCAL_APPS = {LANG_CHN: E_HIDE_LOCAL_APPS_CHN, LANG_ENG: E_HIDE_LOCAL_APPS_ENG}

E_SHOW_SHARED_APPS_CHN = '显示共享应用(&L)'
E_SHOW_SHARED_APPS_ENG = 'Show Shared Apps(&L)'
E_SHOW_SHARED_APPS = {LANG_CHN: E_SHOW_SHARED_APPS_CHN, LANG_ENG: E_SHOW_SHARED_APPS_ENG}

E_HIDE_SHARED_APPS_CHN = '隐藏共享应用(&L)'
E_HIDE_SHARED_APPS_ENG = 'Hide Shard Apps(&L)'
E_HIDE_SHARED_APPS = {LANG_CHN: E_HIDE_SHARED_APPS_CHN, LANG_ENG: E_HIDE_SHARED_APPS_ENG}

E_SHOW_BROWSER_BOOKMARKS_CHN = '显示浏览器书签(&B)'
E_SHOW_BROWSER_BOOKMARKS_ENG = 'Show Browser Bookmarks(&B)'
E_SHOW_BROWSER_BOOKMARKS = {LANG_CHN: E_SHOW_BROWSER_BOOKMARKS_CHN, LANG_ENG: E_SHOW_BROWSER_BOOKMARKS_ENG}

E_HIDE_BROWSER_BOOKMARKS_CHN = '隐藏浏览器书签(&B)'
E_HIDE_BROWSER_BOOKMARKS_ENG = 'Hide Browser Bookmarks(&B)'
E_HIDE_BROWSER_BOOKMARKS = {LANG_CHN: E_HIDE_BROWSER_BOOKMARKS_CHN, LANG_ENG: E_HIDE_BROWSER_BOOKMARKS_ENG}

E_HELP_CHN = '帮助(&H)'
E_HELP_ENG = 'Help(&H)'
E_HELP = {LANG_CHN: E_HELP_CHN, LANG_ENG: E_HELP_ENG}

E_CHECK_UPDATE_CHN = '检查更新(&U)'
E_CHECK_UPDATE_ENG = 'Check Update(&U)'
E_CHECK_UPDATE = {LANG_CHN: E_CHECK_UPDATE_CHN, LANG_ENG: E_CHECK_UPDATE_ENG}

E_ABOUT_CHN = '关于(&A)'
E_ABOUT_ENG = 'About(&A)'
E_ABOUT = {LANG_CHN: E_ABOUT_CHN, LANG_ENG: E_ABOUT_ENG}

E_RMV_TAG_CHN = '删除标签(&D)'
E_RMV_TAG_ENG = 'Remove Tag(&D)'
E_RMV_TAG = {LANG_CHN: E_RMV_TAG_CHN, LANG_ENG: E_RMV_TAG_ENG}

E_SRT_APP_CHN = '排序应用(&S)'
E_SRT_APP_ENG = 'Sort App(&S)'
E_SRT_APP = {LANG_CHN: E_SRT_APP_CHN, LANG_ENG: E_SRT_APP_ENG}

E_NEW_APP_CHN = '新建应用(&A)'
E_NEW_APP_ENG = 'New App(&A)'
E_NEW_APP = {LANG_CHN: E_NEW_APP_CHN, LANG_ENG: E_NEW_APP_ENG}

E_REFRESH_CHN = '刷新(&R)'
E_REFRESH_ENG = 'Refresh(&R)'
E_REFRESH = {LANG_CHN: E_REFRESH_CHN, LANG_ENG: E_REFRESH_ENG}

E_MOD_APP_CHN = '修改应用(&M)'
E_MOD_APP_ENG = 'Modify App(&M)'
E_MOD_APP = {LANG_CHN: E_MOD_APP_CHN, LANG_ENG: E_MOD_APP_ENG}

E_RMV_APP_CHN = '删除应用(&D)'
E_RMV_APP_ENG = 'Remove App(&D)'
E_RMV_APP = {LANG_CHN: E_RMV_APP_CHN, LANG_ENG: E_RMV_APP_ENG}

E_RUN_APP_CHN = '运行应用(&R)'
E_RUN_APP_ENG = 'Run App(&R)'
E_RUN_APP = {LANG_CHN: E_RUN_APP_CHN, LANG_ENG: E_RUN_APP_ENG}

E_SHARE_APP_CHN = '分享应用(&S)'
E_SHARE_APP_ENG = 'Share App(&S)'
E_SHARE_APP = {LANG_CHN: E_SHARE_APP_CHN, LANG_ENG: E_SHARE_APP_ENG}

E_OPEN_APP_PATH_CHN = '打开应用路径(&O)'
E_OPEN_APP_PATH_ENG = 'Open App Path (&O)'
E_OPEN_APP_PATH = {LANG_CHN: E_OPEN_APP_PATH_CHN, LANG_ENG: E_OPEN_APP_PATH_ENG}

E_COPY_APP_PATH_CHN = '复制应用路径(&C)'
E_COPY_APP_PATH_ENG = 'Copy App Path(&C)'
E_COPY_APP_PATH = {LANG_CHN: E_COPY_APP_PATH_CHN, LANG_ENG: E_COPY_APP_PATH_ENG}

E_OPEN_CLASSIFICATION = '打开类别(&E)'
E_OPEN_CLASSIFICATION_ENG = 'Open Classification(&E)'

E_SYSTRAY_SHOW_CHN = '显示界面'
E_SYSTRAY_SHOW_ENG = '显示界面'
E_SYSTRAY_SHOW = {LANG_CHN: E_SYSTRAY_SHOW_CHN, LANG_ENG: E_SYSTRAY_SHOW_ENG}

E_SYSTRAY_HIDE_CHN = '隐藏界面'
E_SYSTRAY_HIDE_ENG = '隐藏界面'
E_SYSTRAY_HIDE = {LANG_CHN: E_SYSTRAY_HIDE_CHN, LANG_ENG: E_SYSTRAY_HIDE_ENG}

E_SYSTRAY_QUIT_CHN = '退出'
E_SYSTRAY_QUIT_ENG = '退出'
E_SYSTRAY_QUIT = {LANG_CHN: E_SYSTRAY_QUIT_CHN, LANG_ENG: E_SYSTRAY_QUIT_ENG}

E_ACTIVE_TAG_CHN = '活动标签'
E_ACTIVE_TAG_ENG = 'Active Tag'
E_ACTIVE_TAG = {LANG_CHN: E_ACTIVE_TAG_CHN, LANG_ENG: E_ACTIVE_TAG_ENG}

E_DOWNLOAD_KEY = '-DOWNLOAD-KEY-'
E_DOWNLOAD_END = '-DOWNLOAD-END-'
E_DEFAULT = 'default'

APP_TITLE_CHN = '工作助手'
APP_TITLE_ENG = 'Work Helper'
E_SEARCH_CHN = '搜索'
E_SEARCH_ENG = 'Search'
E_RETURN_CHN = '返回上一级'
E_RETURN_ENG = 'Return'
ALL_APPS_CHN = '全部应用'
ALL_APPS_ENG = 'All Apps'
MY_APPS_CHN = '我的应用'
MY_APPS_ENG = 'My Apps'
LOCAL_APPS_CHN = '本地应用'
LOCAL_APPS_ENG = 'Local Apps'
SHARED_APPS_CHN = '共享应用'
SHARED_APPS_ENG = 'Shared Apps'
ALL_BOOKMARKS_CHN = '全部书签'
ALL_BOOKMARKS_ENG = 'All Bookmarks'
CHROME_BOOKMARKS_CHN = '谷歌书签'
CHROME_BOOKMARKS_ENG = 'Chrome Bookmarks'
EDGE_BOOKMARKS_CHN = '微软书签'
EDGE_BOOKMARKS_ENG = 'Edge Bookmarks'
FIREFOX_BOOKMARKS_CHN = '火狐书签'
FIREFOX_BOOKMARKS_ENG = 'Firefox Bookmarks'
UNKNOWN_BOOKMARKS_CHN = '未知书签'
UNKNOWN_BOOKMARKS_ENG = 'Unknown Bookmarks'
APP_FONT_CHN = ('Helvetica', 11)
APP_FONT_ENG = ('Helvetica', 11)
APP_ICON_PATH = 'image'
FONT_FAMILY = ['Helvetica', 'Courier', ]

APP_ICON = 'workhelper.ico'
APP_DB = 'workhelper.db'
APP_LOG = 'workhelper.log'
APP_EXE = 'workhelper.exe'
APP_VERSION = '1.0.0'
APP_ROOT = 'my'
APP_THEME = 'DarkGreen'


APP_TITLE = {LANG_CHN: APP_TITLE_CHN, LANG_ENG: APP_TITLE_ENG}
APP_FONT = {LANG_CHN: APP_FONT_CHN, LANG_ENG: APP_FONT_ENG}
ALL_APPS = {LANG_CHN: ALL_APPS_CHN, LANG_ENG: ALL_APPS_ENG}
MY_APPS = {LANG_CHN: MY_APPS_CHN, LANG_ENG: MY_APPS_ENG}
LOCAL_APPS = {LANG_CHN: LOCAL_APPS_CHN, LANG_ENG: LOCAL_APPS_ENG}
SHARED_APPS = {LANG_CHN: SHARED_APPS_CHN, LANG_ENG: SHARED_APPS_ENG}
ALL_BOOKMARKS = {LANG_CHN: ALL_BOOKMARKS_CHN, LANG_ENG: ALL_BOOKMARKS_ENG}
CHROME_BOOKMARKS = {LANG_CHN: CHROME_BOOKMARKS_CHN, LANG_ENG: CHROME_BOOKMARKS_ENG}
EDGE_BOOKMARKS = {LANG_CHN: EDGE_BOOKMARKS_CHN, LANG_ENG: EDGE_BOOKMARKS_ENG}
FIREFOX_BOOKMARKS = {LANG_CHN: FIREFOX_BOOKMARKS_CHN, LANG_ENG: FIREFOX_BOOKMARKS_ENG}
UNKNOWN_BOOKMARKS = {LANG_CHN: UNKNOWN_BOOKMARKS_CHN, LANG_ENG: UNKNOWN_BOOKMARKS_ENG}
E_SEARCH = {LANG_CHN: E_SEARCH_CHN, LANG_ENG: E_SEARCH_ENG}
E_RETURN = {LANG_CHN: E_RETURN_CHN, LANG_ENG: E_RETURN_ENG}

# SHOW VIEW TYPE
SHOW_ICON = 0
SHOW_LIST = 1

# SHOW SORT TYPE
SORT_DEFAULT = 1
SORT_ASCEND = 2
SORT_DESCEND = 3
SORT_PREFERRED = 4
