# -*- coding: utf-8 -*-

E_FILE = '文件(&F)'
E_IMPORT_APPS_INFO = '导入应用信息(&I)'
E_EXPORT_APPS_INFO = '导出应用信息(&X)'
E_QUIT = '退出(&Q)'
E_EDIT = '编辑(&E)'
E_MANAGE_TAG = '管理标签(&M)'
E_NEW_TAG = '新建标签(&N)'
E_MOD_TAG = '编辑标签'
E_VIEW = '视图(&V)'
E_SHOW_ICON_VIEW = '图标显示(&G)'
E_SHOW_LIST_VIEW = '列表显示(&L)'
E_OPTION = '选项(&S)'
E_SELECT_ROOT = '选择根目录(&O)'
E_SELECT_THEME = '选择主题(&T)'
E_SHOW_LOCAL_APPS = '显示本地应用(&L)'
E_HIDE_LOCAL_APPS = '隐藏本地应用(&L)'
E_SHOW_BROWSER_BOOKMARKS = '显示浏览器书签(&B)'
E_HIDE_BROWSER_BOOKMARKS = '隐藏浏览器书签(&B)'
E_SELECT_FONT = '选择字体(&F)'
E_SET_WINDOW = '设置窗口(&W)'
E_HELP = '帮助(&H)'
E_CHECK_UPDATE = '检查更新(&U)'
E_ABOUT = '关于(&A)'
E_RMV_TAG = '删除标签(&D)'
E_SRT_APP = '排序应用(&S)'
E_NEW_APP = '新建应用(&A)'
E_REFRESH = '刷新(&R)'
E_MOD_APP = '修改应用(&M)'
E_RMV_APP = '删除应用(&D)'
E_RUN_APP = '运行应用(&R)'
E_OPEN_APP_PATH = '打开应用路径(&O)'
E_COPY_APP_PATH = '复制应用路径(&C)'
E_OPEN_CLASSIFICATION = '打开类别'
E_ACTIVE_TAG = '活动标签'
E_THREAD = '-THREAD-'
E_DOWNLOAD_END = '-DOWNLOAD-END-'
E_SYSTRAY_SHOW = '显示界面'
E_SYSTRAY_HIDE = '隐藏界面'
E_SYSTRAY_QUIT = '退出'
E_DEFAULT = 'default'

APP_TITLE_CHN = '工作助手'
APP_TITLE_ENG = 'Work Helper'
E_SEARCH_CHN = '搜索'
E_SEARCH_ENG = 'Search'
E_RETURN_CHN = '返回上一级'
E_RETURN_ENG = 'Return'

ALL_APPS_CHN = '全部应用'
ALL_APPS_ENG = 'All Apps'
MY_APPS_CHN = '我的应用'
MY_APPS_ENG = 'My Apps'
LOCAL_APPS_CHN = '本地应用'
LOCAL_APPS_ENG = 'Local Apps'
ALL_BOOKMARKS_CHN = '全部书签'
ALL_BOOKMARKS_ENG = 'All Bookmarks'
CHROME_BOOKMARKS_CHN = '谷歌书签'
CHROME_BOOKMARKS_ENG = 'Chrome Bookmarks'
EDGE_BOOKMARKS_CHN = '微软书签'
EDGE_BOOKMARKS_ENG = 'Edge Bookmarks'
FIREFOX_BOOKMARKS_CHN = '火狐书签'
FIREFOX_BOOKMARKS_ENG = 'Firefox Bookmarks'
UNKNOWN_BOOKMARKS_CHN = '未知书签'
UNKNOWN_BOOKMARKS_ENG = 'Unknown Bookmarks'

APP_ICON = 'workhelper.ico'
APP_DB = 'workhelper.db'
APP_LOG = 'workhelper.log'
APP_EXE = 'workhelper.exe'
APP_VERSION = '1.0.0'
APP_ROOT = 'root'
APP_THEME = 'DarkGreen'
APP_FONT = ('Helvetica', 11)
APP_ICON_PATH = 'image'
FONT_FAMILY = ['Helvetica', 'Courier', ]

APP_TITLE = APP_TITLE_CHN
ALL_APPS = ALL_APPS_CHN
MY_APPS = MY_APPS_CHN
LOCAL_APPS = LOCAL_APPS_CHN
ALL_BOOKMARKS = ALL_BOOKMARKS_CHN
CHROME_BOOKMARKS = CHROME_BOOKMARKS_CHN
EDGE_BOOKMARKS = EDGE_BOOKMARKS_CHN
FIREFOX_BOOKMARKS = FIREFOX_BOOKMARKS_CHN
UNKNOWN_BOOKMARKS = UNKNOWN_BOOKMARKS_CHN
E_SEARCH = E_SEARCH_CHN
E_RETURN = E_RETURN_CHN

SHOW_ICON = 0
SHOW_LIST = 1

SORT_DEFAULT = 1
SORT_ASCEND = 2
SORT_DESCEND = 3
SORT_PREFERRED = 4
